apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.deployments.keycloak.service.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.deployments.keycloak.service.name }}"
spec:
  ports:
    - name: https
      port: {{.Values.deployments.securePort}}
      targetPort: {{.Values.deployments.keycloak.ports.containerPort}}
  selector:
    app: "{{ .Values.deployments.keycloak.service.name }}"
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.deployments.keycloak.service.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.deployments.keycloak.service.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.deployments.keycloak.service.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.deployments.keycloak.service.name }}"
    spec:
      containers:
        - name: "{{ .Values.deployments.keycloak.service.name }}"
          image: quay.io/keycloak/keycloak:21.0.2
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_ADMIN
                  name: "{{ .Values.secrets.keycloak.name }}"
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_ADMIN_PASSWORD
                  name: "{{ .Values.secrets.keycloak.name }}"
            - name: KC_PROXY
              value: "edge"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "true"
            - name: KC_LOG_LEVEL
              value: INFO
            - name: DB_VENDOR
              value: POSTGRES
            - name: DB_ADDR
              value: "{{ .Values.deployments.postgres.service.name }}"
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secrets.postgres.name }}"
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secrets.postgres.name }}"
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secrets.postgres.name }}"
                  key: POSTGRES_PASSWORD
          ports:
            - name: http
              containerPort:
                {{.Values.deployments.keycloak.ports.containerPort}}
          readinessProbe:
            httpGet:
              path: /health/ready
              port: {{.Values.deployments.keycloak.ports.containerPort}}
            initialDelaySeconds: 250
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: {{.Values.deployments.keycloak.ports.containerPort}}
            initialDelaySeconds: 500
            periodSeconds: 30
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
